### ISSUE TITLE
Categorize the downloaded zip files into a folder to prevent confusion caused by too many zip files

### ISSUE THREAD

**Issue by zisen123** [debkbanerji/minecraft-bedrock-server#5]
After each update it wll download a `bedrock-server-1.xx.zip` in the directory and leave a directory `bedrock-server-1.xx` which is no useful anymore.
I suggest create a directory `server_downloads` to storage these `bedrock-server-1.xx.zip` and only one directory like `your_server` to place the server files, it will much neater.

**Comment by debkbanerji** [comment]
Will look into this, but cleaning up/moving old servers in the event of an upgrade can be very dangerous. While the backup system should preserver old worlds, in the event of an improper shutdown, the world state present in those old worlds could theoretically be helpful in the event of a failure. Categorization may be less risky, so I'll look into this as long as backward compatibility can be maintained. Cleaning up old zip files should be fairly easy either way, though - it's probably best to delete these after unzipping.

**Comment by debkbanerji** [comment]
I added in a non destructive implementation in 2021.12.1 with backwards compatibility - basically, it doesn't delete old server versions, but starts storing any new ones in a `servers` folder. Zip files for new servers are now also removed after being unpacked since they're not required.
